// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRzJaixx0BgwihnPo0cav1_MXfXvMBuL4',
    appId: '1:335134128874:web:1b1b9d40b97caeb5c87593',
    messagingSenderId: '335134128874',
    projectId: 'fir-coffee-yeter',
    authDomain: 'fir-coffee-yeter.firebaseapp.com',
    storageBucket: 'fir-coffee-yeter.appspot.com',
    measurementId: 'G-7555RHXV50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD52pZEeUer8AotxQgV5bXeQfYEUadQj20',
    appId: '1:335134128874:android:0163567542b95de2c87593',
    messagingSenderId: '335134128874',
    projectId: 'fir-coffee-yeter',
    storageBucket: 'fir-coffee-yeter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd9shwR_AiCVh5A7TGWpjMdYlvc7Opn5o',
    appId: '1:335134128874:ios:e4b9f8622ff3b433c87593',
    messagingSenderId: '335134128874',
    projectId: 'fir-coffee-yeter',
    storageBucket: 'fir-coffee-yeter.appspot.com',
    iosClientId: '335134128874-6reucbfpi07brje8kaa3bnpvhoh13au1.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeyeter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd9shwR_AiCVh5A7TGWpjMdYlvc7Opn5o',
    appId: '1:335134128874:ios:95e3042324a160b2c87593',
    messagingSenderId: '335134128874',
    projectId: 'fir-coffee-yeter',
    storageBucket: 'fir-coffee-yeter.appspot.com',
    iosClientId: '335134128874-s3mskleot88f1s8khbn26o7q73jebf8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeyeter.RunnerTests',
  );
}
